[package]
name = "byte_common"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = { version = "0.25", features = ["derive"] }

[build-dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
